# Executed from Vagrant
# Can be run also manually, as user vagrant, with: `ansible-playbook docker-vm-provisioning.yml -i inventory`
# Add -v for verbose or -vvv for more
---

- name: Configure CentOS7 with Docker
  hosts: dkr
  tasks:
    # ==> Upgrade all packages
    - name: Upgrade all packages
      become: yes
      yum:
        name: '*'
        state: latest

    # ==> Install repos, for latest python, pip
    - name: Install IUS repo
      become: yes
      yum:
        name:
          - "https://repo.ius.io/ius-release-el7.rpm"
          - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
        state: present

    # ==> Install packages: tree and unzip are optional, jq is used for some docker commands, pip is used for docker-compose
    - name: Install packages
      become: yes
      yum:
        name:
          - tree
          - unzip
          - python-pip
          - jq
        state: present

    # ==> Upgrade pip
    - name: Upgrade pip
      become: yes
      pip:
        name: pip
        state: latest

    # ==> Install packages for docker
    # - name: Install dependencies packages for docker
    #   become: yes
    #   yum:
    #     name:
    #       - yum-utils
    #       - device-mapper-persistent-data
    #       - lvm2
    #     state: present

    # ==> Install Docker CE

    - name: Add the docker-ce stable repository
      become: yes
      shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install docker-ce
      become: yes
      yum:
        name:
          - docker-ce
        state: present

    - name: Start docker
      become: yes
      systemd:
        daemon_reload: yes
        state: started
        enabled: yes
        name: docker

    - name: Add user to group docker, to be able to run docker commands without sudo
      become: yes
      user:
        name: "{{ ansible_env.USER }}"
        groups: docker
        append: yes

    - name: Install docker sdk for python
      # become: yes
      pip:
        name: docker
        extra_args: --user
        state: present

    # - name: Install docker-compose
    #   # become: yes
    #   pip:
    #     name: docker-compose
    #     extra_args: --user
